name: chance
version: 3.1.2
description: A minimalist set of functions to generate random numbers, strings etc.
homepage: https://github.com/r-unruh/chance

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.23.1
