name: chance
version: 3.0.0
description: A minimalist collection of random number generator functions
homepage: https://github.com/r-unruh/chance

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.23.1
